baseURL = "https://www.jackhansom.netlify.app/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Jack Hansom CV"
    author = "Jack Hansom"
    description = "Jack Hansom's CV wesite"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Jack Hansom"
		tagline = "Data Scientist"
		location = "London"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "#"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I'm a quantum physicist by training, working on applying machine learning and data science to a variety of problems since 2015"

    # Experience section
    [params.experience]
        title = "Work Experience"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Principal Data Scientist"
            dates = "October 2019 - *Present*"
            company = "Verv"
            details = "Developing machine learning models and architecture for real-time [fault detection](blog/fault_detection) of electrical household appliances."
        [[params.experience.list]]
            position = "Data Scientist"
            dates = "October 2017 - October 2019"
            company = "Verv"
            details = "Developing machine learning models and architecture for real-time [appliance disaggregation](blog/NILM) of electrical household appliances."
        [[params.experience.list]]
            position = "Data Scientist"
            dates = "September 2015 - October 2017"
            company = "SCL Elections"
            details = "Working as a data scientist with a political communications strategy company with an emphasis on using machine learning and data science for microtargeting."
        [[params.experience.list]]
            position = "Data Science Fellow"
            dates = "Summer 2015"
            company = "The ASI (now Faculty)"
            details = "Highly selective and intensive 8 week [course](https://faculty.ai/products-services/fellowship/) providing fellows a taught component and an individual project with a company."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Physics"
            college = "University of Cambridge"
            dates = "2011 - 2015"
            thesis_title = "Environmental coupling in quantum dot as a resource for quantum optics and spin control"
            thesis_link = "https://www.repository.cam.ac.uk/handle/1810/252641"
        [[params.education.list]]
            degree = "MSci in Physics"
            college = "University College London"
            dates = "2007 - 2011"
            thesis_title = "Coupling entropy in quantum systems."
        [[params.education.list]]
            degree = "French Baccalaureat, specializing in science"
            college = "Riberac"
            dates = "2007"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Machine Learning", "Physics"]

        [[params.publication.list]]
            title = "Deep Neural Networks for Appliance Transient Classification."
            authors = "Peter Davies, Jon Dennis, Jack Hansom, William Martin, Aistis Stankevicius, Lionel Ward"
            date = "2019"
            journal = "IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)"
            link = "https://ieeexplore.ieee.org/document/8682658"
            type = "Machine Learning"

        [[params.publication.list]]
            title = "Quadrature squeezed photons from a two-level system."
            authors = "C. H. H. Schulte, J. Hansom, et all"
            date = "2015"
            journal = "Nature, 525, 222-225 (2015)"
            link = "https://www.nature.com/articles/nature14868"
            type = "Physics"
		
        [[params.publication.list]]
            title = "Environment-assisted quantum control of a solid-state spin via coherent dark states."
            authors = "J. Hansom, et al"
            date = "2014"
            journal = "Nature Physics, 10, 725 (2014)"
            link = "https://www.nature.com/articles/nphys3077"
            type = "Physics"

        [[params.publication.list]]
            title = "Frequency stabilization of the zero-phonon line of a quantum dot via phonon-assisted active feedback."
            authors = "J. Hansom, et al"
            date = "2014"
            journal = "Applied Physics Letters, 105, 172107"
            link = "https://aip.scitation.org/doi/abs/10.1063/1.4901045?journalCode=apl"
            type = "Physics"

        [[params.publication.list]]
            title = "Dynamics of a mesoscopic nuclear spin ensemble interacting with an optically driven electron spin."
            authors = "M. J. Stanley, et al"
            date = "2014"
            journal = "Phys. Rev. B 90, 195305"
            link = "https://journals.aps.org/prb/abstract/10.1103/PhysRevB.90.195305"
            type = "Physics"

        [[params.publication.list]]
            title = "Phase-locked indistinguishable photons withsynthesized waveforms from a solid-state source."
            authors = "C. Matthiesen, et al"
            date = "2013"
            journal = "Nature Communications volume 4, Article number: 1600 (2013) "
            link = "https://www.nature.com/articles/ncomms2601"
            type = "Physics"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Probabilistic football predictions"
            url = "https://jackhansom.github.io//data%20science/2018WorldCup/"
            description = "Simple probabilistic modelling of the 2018 world cup"
        [[params.project.list]]
            title = "Spark raspberry-pi mini cluster"
            url = "https://jackhansom.github.io//data%20science/Raspberry-Pi-3-Spark-Cluster/"
            description = "Created a home spark cluster based on raspberry-pi machines"
        [[params.project.list]]
            title = "2017 French elections tweet graph"
            url = "https://jackhansom.github.io//data%20science/FrenchPrimaries/"
            description = "Simple visualisation of tweets collected during the 2017 French presidential elections"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python"
            skillrating = 90        
        [[params.skill.list]]
            skill = "Scala"
            skillrating = 40
        [[params.skill.list]]
            skill = "C++"
            skillrating = 30
        [[params.skill.list]]
            skill = "Spark"
            skillrating = 60
        [[params.skill.list]]
            skill = "Javascript"
            skillrating = 30
        [[params.skill.list]]
            skill = "Data Analysis"
            skillrating = 90
        [[params.skill.list]]
            skill = "Machine Learning"
            skillrating = 90
        [[params.skill.list]]
            skill = "Statistics"
            skillrating = 80
        [[params.skill.list]]
            skill = "Deep Learning"
            skillrating = 70
        [[params.skill.list]]
            skill = "Bayesian methods"
            skillrating = 70
        [[params.skill.list]]
            skill = "cloud ML deployment"
            skillrating = 70
        [[params.skill.list]]
            skill = "edge ML deployment"
            skillrating = 40

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Running"
        [[params.hobby.list]]		
		    hobby = "Cycling"
        [[params.hobby.list]]		
		    hobby = "Piano"